services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: aryon
      POSTGRES_PASSWORD: aryon
      POSTGRES_DB: aryondb
    ports:
      - "5432:5432"
    networks:
      - aryon-network

  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    container_name: python-api
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://aryon:aryon@postgres:5432/aryondb?sslmode=disable
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - postgres
    networks:
      - aryon-network

  go-server:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://aryon:aryon@postgres:5432/aryondb?sslmode=disable
    depends_on:
      - postgres
    networks:
      - aryon-network

networks:
  aryon-network:
    driver: bridge