services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
      DEFAULT_REGION: us-east-2
    volumes:
      - localstack_data:/tmp/localstack
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine  # Using Alpine for smaller image
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aryon
      POSTGRES_PASSWORD: aryon
      POSTGRES_DB: aryon
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  localstack_data:
    name: aryon_localstack_data
  postgres_data:
    name: aryon_postgres_data

networks:
  default:
    name: aryon_network