services:
  grpcserver:
    container_name: grpc_server
    build:
        context: .
        dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      - SERVICE_NAME=slack-connector
      - PORT=50051
      - LOG_LEVEL=info
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - localstack
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 3
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_aws
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
      DEFAULT_REGION: us-east-2
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: aryon
      POSTGRES_PASSWORD: aryon
      POSTGRES_DB: aryondb
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  localstack_data:
  postgres_data:

networks:
  default:
    name: aryon_network